### ISSUE TITLE
get enormous errors using the same Unity Version

### ISSUE THREAD

**Issue by lukeskyyyyy** [justinpbarnett/visionos-demo#1]

**Comment by justinpbarnett** [comment]
Care to describe the errors?

**Comment by rajat844** [comment]
Try adding oculus integration package. You have to add that to my assets first. This will solve the errors. But might not still run cause there are no meta files for prefabs. So the whole link is broken.

**Comment by justinpbarnett** [comment]
Resolved! Had not uploaded the .meta files. Accidentally had them ignored in the .gitignore file.
